  language: python
  python:
    - "2.7"
    - "3.5"
  install:
    - pip install codecov
  script:
    - python -m unittest polynomial_tests
    - coverage run polynomial_tests.py
  after_success:
    - codecov
  email:
  on_success: change
  on_failure: always
